# Generated by Django 5.2.8 on 2025-11-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_player_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
