# Generated by Django 5.2.8 on 2025-11-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_defense_playerevaluation_agility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attendance_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
